name: Build & Push CryWolf Images

on:
  push:
    branches: ["main"]

env:
  AWS_REGION: ap-northeast-2
  AWS_ACCOUNT_ID: 515966508618

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: ConfigureAWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ evn.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build & Push Images
        run: |
          REGISTRY="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"
          TAG="${GITHUB_SHA}"

          # ==== API ====
          docker build -t ${REGISTRY}/crywolf/api:${TAG} -t ${REGISTRY}/crywolf/api:latest -f APIServer/DockerfileAPI .
          docker push ${REGISTRY}/crywolf/api:${TAG}
          docker push ${REGISTRY}/crywolf/api:latest

          # ==== Web ====
          docker build -t ${REGISTRY}/crywolf/web:${TAG} -t ${REGISTRY}/crywolf/web:latest -f WebSite/DockerfileWeb .
          docker push ${REGISTRY}/crywolf/web:${TAG}
          docker push ${REGISTRY}/crywolf/web:latest

          # ==== Matchmaking ====
          docker build -t ${REGISTRY}/crywolf/matchmaking:${TAG} -t ${REGISTRY}/crywolf/matchmaking:latest -f MatchMaking/DockerfileMatchMaking .
          docker push ${REGISTRY}/crywolf/matchmaking:${TAG}
          docker push ${REGISTRY}/crywolf/matchmaking:latest

          # ==== Proxy ====
          docker build -t ${REGISTRY}/crywolf/proxy:${TAG} -t ${REGISTRY}/crywolf/proxy:latest -f Proxy/DockerfileProxy .
          docker push ${REGISTRY}/crywolf/proxy:${TAG}
          docker push ${REGISTRY}/crywolf/proxy:latest
